chore: Activate project-manager in demo environment
samply/lens pull request #136
Opened 2024-10-02 10:18 UTC by torbrenner

2024-10-15 07:49 UTC, patrick-skowronek approved these changes

2024-10-16 12:32 UTC, djuarezgf requested changes
I think, we are missing lens-dktk-datashield-test (a second server of Jan), lens-bonn and less-tuebingen

2024-10-16 13:10 UTC, patrickskowronekdkfz commented
> I think, we are missing lens-dktk-datashield-test (a second server of Jan), lens-bonn and less-tuebingen

I added dktk-datashield-test, I'm not aware of Bonn or Tübingen.

2024-10-16 13:11 UTC, Threated approved these changes

2024-10-16 13:12 UTC, merged