feat: add message for empty charts
samply/lens pull request #164
Opened 2024-12-18 14:54 UTC by valeriesauer

### General Summary

### Description
Added a "No Data available" message when the chart contains no data. The message is rendered in the chart when all dataset values are 0 or empty

### Related Issue
https://github.com/samply/lens/issues/160#issue-2744494490

2025-01-15 12:51 UTC, patrickskowronekdkfz requested changes

2025-01-15 12:51 UTC, patrickskowronekdkfz commented on packages/lib/src/components/results/ChartComponent.wc.svelte
> +        if (responseStore.size === 0) {
The logic is not correct, when the responseStore is empty it should be the "empty charts" look like the initial load. If the Store has results but not regarding this Diagramm then it should show the text

2025-01-15 12:51 UTC, patrickskowronekdkfz commented on packages/lib/src/components/results/ChartComponent.wc.svelte
> +        <p>No Data Available</p>
Could you make it less aggressive

2025-02-18 15:51 UTC, timakro commented
I've changed it such that the "No Data Available" message only shows when no responses are pending. It looks like this now:

![image](https://github.com/user-attachments/assets/522ce063-09f5-4b85-aa80-8d1cdf92805d)

Notice that the message is missing from the "Therapieart" chart because there is a single data point with the value 0:

```json
{"labels":["medicationStatements"],"data":[{"data":[0],"backgroundColor":["#4dc9f6","#3da4c7"],"backgroundHoverColor":["#aaaaaa"]}]}
```

Instead of checking if "labels" is empty I could alternatively check if all data points are 0. Should I do that?

2025-02-18 16:02 UTC, timakro commented
I should be done force pushing now...

2025-02-19 07:50 UTC, patrickskowronekdkfz commented
> I've changed it such that the "No Data Available" message only shows when no responses are pending. It looks like this now:
> 
> ![image](https://private-user-images.githubusercontent.com/8438790/414338719-522ce063-09f5-4b85-aa80-8d1cdf92805d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mzk5NDg1NDQsIm5iZiI6MTczOTk0ODI0NCwicGF0aCI6Ii84NDM4NzkwLzQxNDMzODcxOS01MjJjZTA2My0wOWY1LTRiODUtYWE4MC04ZDFjZGY5MjgwNWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMTlUMDY1NzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2JjZjc1MzYxYmRkZjFjYWQ2YTY1MmZmY2Q1OGZmZGJiOGFhNjY5YTVlMzdkY2JiYmVjZDg2ZWI5YjY2NjhjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.2j__s90X-zvNFWhxl_np9lrflNAB2bI_LjD2BoLsypc)
> 
> Notice that the message is missing from the "Therapieart" chart because there is a single data point with the value 0:
> 
> ```json
> {"labels":["medicationStatements"],"data":[{"data":[0],"backgroundColor":["#4dc9f6","#3da4c7"],"backgroundHoverColor":["#aaaaaa"]}]}
> ```
> 
> Instead of checking if "labels" is empty I could alternatively check if all data points are 0. @patrickskowronekdkfz Should I do that?

I think this is the way to go. I'm a bit confused, why we always show a label, even when there is no data

2025-02-19 07:53 UTC, patrickskowronekdkfz requested changes

2025-02-19 07:53 UTC, patrickskowronekdkfz commented on packages/lib/src/styles/result-chart.css
> +lens-chart::part(chart-overlay) {
For some reason it is not in the center. Could you please check it

2025-02-19 09:05 UTC, timakro commented on packages/lib/src/styles/result-chart.css
> +lens-chart::part(chart-overlay) {
It's at the center of the containing card, which also has the advantage that it's center aligned with the chart title. Centering it on the canvas would make things more difficult because then the canvas would have to be a child of the overlay element (you can't put elements inside a canvas afaik). That in turn would mean that the overlay would always have to be present, not only when the text would show. And that would mean that we have to allow mouse events to go through if text is not showing. Overall I don't think it's worth it. Plus it probably wouldn't look centered in the way you want it either because the charts y axis will make it look lopsided even if it is centered on the canvas.

2025-02-19 09:25 UTC, patrickskowronekdkfz approved these changes

2025-02-19 09:25 UTC, merged